import React,{Component} from 'react';
export default class Slider extends Component{
    render(){
        return (
            <div>
                <p>
                    slider
                </p>
                <p>
                    slider
                </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p><p>
                slider
            </p>
            </div>
        )
    }
}